- name: Ensure gpg is installed
  ansible.builtin.apt:
    name: gpg
    state: present

- name: Add Zabbix apt repo key
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    dest: /etc/apt/trusted.gpg.d/zabbix-official-repo.asc
    mode: '0644'

- name: Add Zabbix apt repo
  ansible.builtin.apt_repository:
    repo: "deb https://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install Zabbix Agent 2
  ansible.builtin.apt:
    name: zabbix-agent2
    state: present

- name: Copy Zabbix PSK file
  ansible.builtin.copy:
    src: zabbix-agent-psk
    dest: /etc/zabbix/zabbix-agent-psk
    owner: zabbix
    group: zabbix
    mode: '0400'

- name: Configure Zabbix Agent 2
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: zabbix
    group: zabbix
    mode: '0644'
  register: zabbix_config

- name: Add Zabbix user to Docker group
  ansible.builtin.user:
    name: zabbix
    groups: docker
  ignore_errors: true

- name: Restart Zabbix agent service
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: restarted
    enabled: yes
  when: zabbix_config.changed
