- name: Fix iptables so it works on OCI
  ansible.builtin.iptables:
    chain: INPUT
    action: insert
    rule_num: 1
    jump: ACCEPT

- name: Flush iptables
  ansible.builtin.iptables:
    flush: yes

- name: Save iptables rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
