- name: Install Java JRE 21
  ansible.builtin.apt:
    name: openjdk-21-jre-headless
    state: latest

- name: Create All The Mods 10 folder
  ansible.builtin.file:
    path: /opt/minecraft/atm10
    state: directory
    mode: "770"
    owner: minecraft
    group: minecraft

- name: Accept EULA
  ansible.builtin.copy:
    dest: /opt/minecraft/atm10/eula.txt
    content: eula=true
    mode: "660"
    owner: minecraft
    group: minecraft

- name: Copy server.properties
  ansible.builtin.template:
    src: server.properties.j2
    dest: /opt/minecraft/atm10/server.properties
    mode: "660"
    owner: minecraft
    group: minecraft

- name: Copy whitelist.json
  ansible.builtin.copy:
    src: whitelist.json
    dest: /opt/minecraft/atm10/whitelist.json
    mode: "660"
    owner: minecraft
    group: minecraft

- name: Copy ops.json
  ansible.builtin.copy:
    src: ops.json
    dest: /opt/minecraft/atm10/ops.json
    mode: "660"
    owner: minecraft
    group: minecraft

- name: Copy minecraft.service
  ansible.builtin.template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service
    owner: root
    mode: "644"

- name: Reload systemd daemons
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start server and enable Minecraft service
  ansible.builtin.systemd:
    name: minecraft
    state: started
    enabled: yes
