# Encrypt a var using this
# ansible-vault encrypt_string "mystringhere" --vault-password-file ./ansible-vault-key

# Decrypt a var using this
# Create a file containg just the $ANSIBLE_VAULT... part then run this
# ansible-vault decrypt decryptthisfile.yml

- hosts: minecraft
  become: yes
  roles:
    - roles/enable-auto-update
    - roles/fix-iptables
    - roles/install-minecraft-server-backups
    #- roles/atm10-config
  vars:
    mcrcon_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63643431366130323031316665353132343637323830303336643134333034643636376266313038
          6235356162393565663463343031326439623163316139620a623462616537313933613665363030
          62343534303130633435386139653661613432663665313463306361653664336434313639376537
          6466633631346137380a306633386436633831363135346366393462396563323933326164343137
          65633131313263373462323130376264663332656135366432306138373831633532
    kopia_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35333764613063323862366535323966633839323232363839356231323065616338336630363763
          6538656266643164613563353632383330353735343632360a306138613462636336346562343763
          36613665316438623837616238616163333035346661366137613932316564316266303038393736
          3834346230636339620a376462353736616361663835663038643134306265666231383439393535
          61653262633162396233326135313332383665656362363666656461396264623262
    kopia_b2_bucket_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61633566323732383063343931333265643164666233393734613033623736613334383463303931
          3165343637653862356439313561346536316161343536660a663937396365336439616235333935
          35656234653435386231373364393934333030363836643662613236633130326134396234663238
          3262323537343164620a633831646139373932396338326435333332626237666661626533313862
          34323332363835333764626230353534653239376263373536353236636233633139
    kopia_b2_bucket_key_id: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31623233666533663038336463663735376637646132353961613265613032363062373963613631
          6163353261303633653763313366323063393934653334310a346561336265653236643935343330
          35633566336464346437623132393762326563386234626437653832643261336334353663383265
          3532353836333065390a363239653063303836313639656266393237626463396330373934636561
          62633736333833323664643636353630323964396134623562613166376332373334
    kopia_b2_bucket_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33623834366263626164396335326165356165633934376538376639313239633538646436303635
          6165623965346539366234616133333434356537323336300a623764396266393236623831663763
          39383830623663643562626535666339336662636161346232303832343634636337613161363165
          3631366665336234330a353263626237343662396466343262623630366434656561303939613636
          66663765386138393934343765356538643630303035346663626432616536303162
